### ISSUE TITLE
unreachable/duplicated code

### ISSUE THREAD

**Issue by lehrblogger** [ericf/urljs#1]
In the function `port` in url.js, it looks like there is unreachable code at line 314:

<pre>return ( arguments.length ? this._set(PORT, port) : this._url[PORT] );</pre>

that is functionally the same as what immediately precedes it:

<pre>if (arguments.length) {
    return this._set(PORT, port);
} else {
  return this._url[PORT];
}</pre>

Not a huge deal, but JSLint was complaining :)

Thanks!

**Comment by ericf** [comment]
Yeah you’re right; good catch!
